package com.takkas.modules.notification.domain.enums;

public enum NotificationType {
    APPLICATION_RECEIVED, APPLICATION_ACCEPTED, APPLICATION_REJECTED,
    NEW_MESSAGE, OFFER_RECEIVED, OFFER_ACCEPTED, OFFER_REJECTED,
    COUPON_ISSUED, COUPON_EXPIRING_SOON, COUPON_EXPIRED,
    SWAP_OFFER_RECEIVED, SWAP_OFFER_ACCEPTED, SWAP_OFFER_REJECTED, SWAP_COMPLETED,
    SUBSCRIPTION_RENEWED, SUBSCRIPTION_PAYMENT_FAILED, PLAN_UPGRADED
}
